MAX_ITERATIONS = 40
DEBUG = False
PRETTY_LOG = True
USED_MODELS = ['Baseline', 'SDBN', 'UBM', 'UBM-IA', 'EB_UBM', 'EB_UBM-IA', 'DCM', 'DCM-IA', 'DBN', 'DBN-IA']
MIN_DOCS_PER_QUERY = 10
MAX_DOCS_PER_QUERY = 10
SERP_SIZE = 10
EXTENDED_LOG_FORMAT = False

TRANSFORM_LOG = False
QUERY_INDEPENDENT_PAGER = False

TRAIN_FOR_METRIC = False
PRINT_EBU_STATS = True

