MAX_ITERATIONS = 40
DEBUG = False
PRETTY_LOG = True
USED_MODELS = ['Baseline', 'SDBN', 'UBM', 'UBM-IA', 'EB_UBM', 'EB_UBM-IA', 'DCM', 'DCM-IA', 'DBN', 'DBN-IA']
MAX_NUM = 10
SERP_SIZE = 10
EXTENDED_LOG_FORMAT = False
TRANSFORMED_LOG = False

TRAIN_FOR_METRIC = False

